package com.example.tools;

import java.util.HashMap;

// 这是一个缓存
// 使用 MyFun extents Function<T> T=返回类型
// 使用 key = MyFun.hashcode() && MyFun.equals() 作为缓存key (generated by vscode -> Source actions...)
// 使用方法见 psvm 和 MyFun
class Cache<T> extends HashMap<Function<T>, T>{

  Cache() {
    super();
  }

  public T run(Function<T> function) {
    return runOrCached(function, function);
  }

  // public boolean containsKey(Object keyObject) {
  //   return containsKey(keyObject);
  // }

  public T runOrCached(Object keyObject, Function<T> function) {
    if (containsKey(keyObject)) {
      return get(keyObject);
    }
    return cache(function);
  }

  // public T put(Function<T> function, T result) {
  //   return super.put(function, result);
  // }

  public T cache(Function<T> function) {
    T result = function.run();
    put(function, result);
    return result;
  }

  public static void main(String[] args) {
    Cache<String> cache = new Cache<>();
    String r = null;
    r = cache.run(new MyFun(1, 2, 'a', "null"));
    System.out.println(r);
    r = cache.run(new MyFun(1, 2, 'a', "nul2l"));
    System.out.println(r);
    r = cache.run(new MyFun(2, 2, 'a', "nul3l"));
    System.out.println(r);
    r = cache.run(new MyFun(2, 2, 'a', "nul4l"));
    System.out.println(r);
    // null
    // null
    // nul3l
    // nul3l

    // 不行，可能是因为有hashcode。
    // int a = 1;
    // int b = 2;
    // cache.run(() -> {
    // " a "
    // });

  }

}

class MyFun implements Function<String> {

  int a;
  int b;
  char c;
  String s;

  MyFun(int a, int b, char c, String s) {
    this.a = a;
    this.b = b;
    this.c = c;
    this.s = s;
  }

  @Override
  public int hashCode() {
    final int prime = 31;
    int result = 1;
    result = prime * result + a;
    result = prime * result + b;
    return result;
  }

  @Override
  public boolean equals(Object obj) {
    if (this == obj)
      return true;
    if (obj == null)
      return false;
    if (getClass() != obj.getClass())
      return false;
    MyFun other = (MyFun) obj;
    if (a != other.a)
      return false;
    if (b != other.b)
      return false;
    return true;
  }

  @Override
  public String run() {
    return s;
  }
}
